[build]
  command = "pnpm build"
  functions = "netlify/functions"
  publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[dev]
  command = "pnpm dev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
